### ISSUE TITLE
pip package problems with underscore "_" and dash "-" in pkg name

### ISSUE THREAD

**Issue by ijstokes** [conda/conda-env#137]
`conda env export` produced:

```yaml
name: weather_py34
dependencies:
...
- rope=0.9.4=py34_1
...
- pip:
  - rope-py3k-0.9.4==1
```

I do not know how conda came to think there was a `pip` installed version.  What causes `conda env` to identify packages as `pip` installed?  Is it the presence of an egg file?  If so, the egg file `rope_py3k-0.9.4_1-py3.4.egg-info` is inside the `anaconda` channel package here:

https://anaconda.org/anaconda/rope/0.9.4/download/osx-64/rope-0.9.4-py34_1.tar.bz2

In any case, it has the wrong package name, since the `pip` package name is `rope_py3k` not `rope-py3k` as `conda env` has identified.  The effect, one way or another, is that it produces an environment file that cannot be installed by anyone else.

**Comment by ijstokes** [comment]
Perhaps related, `conda env export` is identifying my `anaconda` installed package `sphinx-rtd-theme` as being a `pip` package as well.

```yaml
dependencies:
- sphinx_rtd_theme=0.1.7=py34_0
- pip:
  - sphinx-rtd-theme==0.1.7
```

then results in the warning message:

```bash
Requirement already satisfied (use --upgrade to upgrade): sphinx-rtd-theme==0.1.7 in /Users/carterrees/.conda/envs/weather_py34/lib/python3.4/site-packages
```
