### ISSUE TITLE
New environment format

### ISSUE THREAD

**Issue by malev** [conda/conda-env#145]
Thinking of a new structure for `environment.yml` and trying to capture the spirit of #16, #103, #97 and #15. I'm considering changing the structure into something like:

```yaml
name: stats
conda:
  - numpy
  - javascript/nodejs=0.12.*
  - javascript/bower=1.0.4
  - malev/flask-testing
pip:
  - mock
gem:
  - compass
```
I'm also considering adding the capability of having `jinja2` template, for instance to install specific packages for a OS.

On the other hand `conda env export` should work with the following flags:
  * `--non-strict`
  * `--min-version`
  * `--semver` (I need to think more about this one)

And should include the channels from each package came from.

**Comment by malev** [comment]
Consider using `conda.config.canonical_channel_name(url)` and [conda specs](http://conda.pydata.org/docs/spec.html#package-match-specifications)

**Comment by bkreider** [comment]
Please keep it yaml.  If you add templating, it's hard to create these files and use standard yaml tools. 

Breaking out the type of packages makes it harder to distinguish other top-level fields from possible package managers.   I'd keep it nested under "dependencies" so you don't close off future additions while allowing anyone to add new package managers (ie: specifying a package manager right now implicitly installs a conda package of that name)

**Comment by goanpeca** [comment]
:+1: on  @bkreider suggestion!

**Comment by hale** [comment]
How about a section for platform specific dependencies?

(I'm not sure how this could be determined by `condo env export`, but it would be nice to have a way of creating a config file that could be used to recreate the environment on any platform.)

(Maybe this isn't necessary if `conda env export` only includes top-level dependencies.)

**Comment by yoavram** [comment]
Also note that if the environment was created on a path (using the `-p` option), the name of the environment in the environment.yml file is the full path (`D:\workspace\project\venv`) which breaks the cross-platform feature.

**Comment by Korijn** [comment]
Interesting concept! I wrote a related issue, perhaps we can benefit from eachother's ideas?

See https://github.com/conda/conda-env/issues/200

**Comment by nicoddemus** [comment]
I think we should keep the root `dependencies` item, because it makes straightforward to add backward-compatible features easier, such as the environment variable support proposed in #88. 

So here's my suggestion:

```yml
name: stats
dependencies:
  conda:
    - numpy
    - javascript/nodejs=0.12.*
    - javascript/bower=1.0.4
    - malev/flask-testing
  pip:
    - mock
  gem:
    - compass
```

It could even be made backward compatible by assuming all items under `dependencies` which are not a `dict` are dependencies to be installed using `conda`.
