### ISSUE TITLE
Conda env update doesn't remove installed packages

### ISSUE THREAD

**Issue by nicoddemus** [conda/conda-env#190]
Hi,

Suppose an environment created with the following `environment.yml`:

```yml
name: conda-env-test
dependencies:
  - python
  - py
```

If the user removes `py` from the dependencies list in the file and executes `conda env update` on this environment, `conda-env` won't remove `py` from the environment.

Is this behavior a bug? If so, I would be happy to work on a PR to fix this.
