### ISSUE TITLE
Specify channel in dependencies?

### ISSUE THREAD

**Issue by jlaura** [conda/conda-env#240]
Perhaps I have missed this in the issues / README.  If so, apologies.

```yaml
name: autocnet2
channels:
  - conda-forge
  - jlaura
  - menpo
dependencies:
  - python=3
  - opencv3=3.0.0
  - gdal>1.11.2
  - h5py
```

Given the above specification of dependencies and channels, it is possible to specify which channel a dependency should be filled by?  Something akin to how `pip` is used:

```yaml
name: autocnet2
channels:
  - conda-forge
  - jlaura
  - menpo
dependencies:
  - python=3
  - jlaura:
    - opencv3=3.0.0
  - conda-forge:
    - gdal>1.11.2
  - h5py
```

I also tried specifying the channel as I would required, e.g. opencv=3.0.0 [jlaura].

Is this type of functionality available?
