### ISSUE TITLE
Feature request: recursively process other environment.yml files, and add support for setting environment variables

### ISSUE THREAD

**Issue by campos-ddc** [conda/conda-env#83]
Hi, first of all, thank you for your work in conda/conda-env, these tools are looking great!

Small preface, this feature request might have some relation with #65 and #21.

# Problem
In the company I work for (https://github.com/ESSS), we have the following development process:

* We have many external libraries dependencies, installing them via `conda` works just fine, since they are packages available in our channel (such as numpy, pytest, etc)
* We have many internal libraries that are always in 'development' mode, for these, we do not want to create packages during development. We commonly work in multiple libraries at once, and it would greatly hinder our workflow if we had to recreate packages whenever we make a small change in a dependency and want to test it in another library.

# Scenario
Say for example that we have 2 internal libraries, `DEV-A` and `DEV-B`. `DEV-A` depends on the external library `EXT-A`, while `DEV-B` depends on external libraries `EXT-B` and `EXT-C`.

In this scenario, when working in `DEV-B` I want to be able to:

* 'conda env' a single yaml file for `DEV-B`, that will recursively process the `DEV-A` yaml
* Avoid duplication of dependencies. Since `DEV-B` already depends on `DEV-A`, I should not have to re-declare dependencies that are inherited from `DEV-A`
* Set environment variables necessary to run `DEV-B` in development mode. Since this library is not being installed in a conda virtual environment, I need a way to define paths for its source code and shared libraries.
* Set aliases to be enabled in this environment.

# Proposed solution

I imagined a file that would look something like this, with a few options regarding how to define the environment variables:

```yaml
name: DEV-B

dependencies:
- EXT-2==2.4
- EXT-3==0.3.3

# Recursively process these other environment.yaml files
recurse:
- {{ root }}/../DEV-A/environment.yaml

# Environment option 1 -----------------------------------------------------------------------------
# Add these environment variables. Lists will be joined with os.pathsep. {{ root }} is replaced by
# jinja2, and points to the directory containing this file.
environment:
- PATH:
  - {{ root }}/tools/
  - {{ root }}/artifacts/libs [win]
  
- LD_LIBRARY_PATH:
  - {{ root }}/artifacts/libs [unix]

- PYTHONPATH:
  - {{ root }}/source/python
  - {{ root }}/artifacts/libs

- INCLUDE:
  - {{ root }}/source/c++
  - {{ root }}/source/bindings

alias:
- ptrun: python {{ root }}/tools/ptrun.py

# Environment option 2 -----------------------------------------------------------------------------
# source these scripts when the environment is activated/deactivated.
activate:
- activate.sh  [unix]
- activate.bat [win]

deactivate:
- deactivate.sh  [unix]
- deactivate.bat [win]
```

# Contributing

If we can reach an agreement on the solution, we are willing to implement the whole thing here and open pull-requests to merge the changes back to you.
